---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRESQL_PORT") { "5432" } %>

development:
  primary:
    <<: *default
    database: user_api_development
  queue:
    <<: *default
    database: user_api_queue_development
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: user_api_test

production:
  primary:
    <<: *default
    database: user_api_production
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  queue:
    <<: *default
    database: user_api_queue_development
    migrations_paths: db/queue_migrate
