---
schedule:
  cleanup_unconfirmed_users:
    cron: '*/1 * * * *'  # Every minute (for testing)
    # cron: '0 0 * * *'  # Every day at midnight (for production)
    class: 'CleanupUnconfirmedUsersJob'
    queue: cleanup_unconfirmed_users
    description: "Delete not confirmed users after 24 hours ago"

:queues:
  - cleanup_unconfirmed_users
